### ISSUE TITLE
Lab 1 - which host?

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2016-container-lab#1]
When I did a vagrant up, it did not set the dns name to dev.example.com.  I went ahead and ssh'd into the vagrant host and executed everything from there.

**Comment by dustymabe** [comment]
We need to figure out our DNS strategy for the lab - right now I have just been adding entries to /etc/hosts in the vagrant box. I'll try to get this resolved soon.

**Comment by scollier** [comment]
for purpose of lab, let's leave the hostname to what the cdk defaults are and instead change the lab.  this should ensure OSE works.

**Comment by scollier** [comment]
do global change from dev.example.com to rhel-cdk.example.com in both lab and vagrantifle.

test changes on current by modifying local /etc/hosts.

**Comment by scollier** [comment]
@dustymabe this is ready for testing.  To test this, follow the instructions in the google doc, until you get to this step:

```
/usr/local/bin/getlab # Will download github repo for lab
```

and instead replace with:

```
git clone https://github.com/scollier/summit-2016-container-lab.git
git fetch
git checkout fix-dns-references
```

Then carry on with the rest of the instructions.

You can run the lab visually here:

https://github.com/scollier/summit-2016-container-lab/tree/fix-dns-references/vagrantcdk

Once you say it's good, I'll create a PR and you can merge it in.

**Comment by scollier** [comment]
@dustymabe I think this is all working now.
