### ISSUE TITLE
Starting Lab 2 - bigapp?

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2016-container-lab#10]
I started lab 2 and it takes me to a page "Bulding bigapp".  I had to click on "chapter2.md" to go to the real lab.

**Comment by dustymabe** [comment]
This has to do with the fact that there is a file in those directories called README.md - we can probably just delete the README files as we don't use them in the labs.

**Comment by scollier** [comment]
fixed in #22 

@dustymabe  i'm closing this.
