### ISSUE TITLE
paths are off

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2016-container-lab#14]
i did a git clone of the summit-2016-container-lab and the paths were off a bit for me in lab 3:

mkdir ~/workspace
cd ~/workspace
cp -R ~/labs/lab3/mariadb .
cp -R ~/labs/lab3/wordpress .
ls -lR mariadb
ls -lR wordpress

**Comment by dustymabe** [comment]
What paths are wrong? they look right to me

**Comment by scollier** [comment]
worked for me today.
