### ISSUE TITLE
lab 3 - don't remove wordpress

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2016-container-lab#17]
last command on lab 3 has us remove all stopped containers.  

```
docker rm $(docker ps -qa)
```

In this case, since I stopped openshift, all those containers are stopped, and they would be removed.  so, at this point, do we restart openshift, and then remove all stopped containers?  Or, just remove openshift stopped containers and carry-on?

**Comment by dustymabe** [comment]
we no longer start openshift before this point
