### ISSUE TITLE
chapter 4, xip.io 

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2016-container-lab#25]
no concerns with using upstream / external dynamic dns?  any other solutions?

**Comment by dustymabe** [comment]
You'll notice in the "labvm" that I have an entry for each "external" dns request that gets made in /etc/hosts. I executed the lab completely offline so I'm fairly confident this works. I encourage you to confirm in an independent way.

**Comment by dustymabe** [comment]
@scollier ??

**Comment by scollier** [comment]
Worked last time i tried it.
