### ISSUE TITLE
cpu vmx feature

### ISSUE THREAD

**Issue by langdon** [dustymabe/summit-2016-container-lab#30]
In the virsh vm.xml definition you are using:

```
<cpu mode='host-passthrough'/>
```

I normally use something to require the "vmx" feature of the cpu (like below). 

```
<cpu>
  <feature policy='require' name='vmx'/>
</cpu>
```

However, I am not terribly familiar with how this works, so host-pasthrough may be more than sufficient.

**Comment by dustymabe** [comment]
I've only ever used host-passthrough, because it tries to use the host cpu type in the guest. If the host supports vmx then the guest will get it. 

```
<cpu mode='host-passthrough'/>
  <feature policy='require' name='vmx'/>
</cpu>
```

maybe? Doesn't really matter as long as it works.
