### ISSUE TITLE
vagrant only as root

### ISSUE THREAD

**Issue by langdon** [dustymabe/summit-2016-container-lab#31]
Right now, we have vagrant setup (because virsh is) to only be usable by root. Is that what we want for the lab? Or should we "fix" the virsh setup? And/or, do you want to fix it in the intro? or on the VM itself?

**Comment by dustymabe** [comment]
What do you mean we only have vagrant set up to be usable by root? you should be able to run everything as the "student" user. The student user's home directory is where all of the vagrant plugins are installed. 
@whitel can you elaborate?

**Comment by dustymabe** [comment]
@whitel I think we can close this since we verified that we didn't really need root user with your environment?

**Comment by scollier** [comment]
@dustymabe @whitel I didn't use root for anything.
