### ISSUE TITLE
open to modifications around more "Red Hat container good practice"?

### ISSUE THREAD

**Issue by tchughesiv** [dustymabe/summit-2016-container-lab#39]
Some additions could be added to these labs pretty seamlessly, mostly in lab 1 but possibly elsewhere... things like:
 - non-root uid/user
 - atomic help file
 - atomic labels
 - addressing critical vulnerabilities
 - image build versioning??

advanced/fun optional additions before summit...
 - arbirtrary uid (openshift use-case)?
 - systemd in a container?
 - ocp api within container? w/ secrets mention?
 - image signing?

If folks are ok with it... I'd like to fork and make some additions for review, at least the upper components.

**Comment by dustymabe** [comment]
@tchughesiv sounds good. fork/PR as you'd like. 

Keep in mind, though, that we are super limited on time. This year I'm thinking about just getting rid of the last section of the lab because not many people get to it.

**Comment by tchughesiv** [comment]
sounds good... i'll keep it short and probably entirely to the first section of the lab.

**Comment by dustymabe** [comment]
@tchughesiv I created a new repo for 2017. Let's use that: https://github.com/dustymabe/summit-2017-container-lab
