### ISSUE TITLE
Syncing on workstation setup

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2016-container-lab#4]
I did not have this directory:

As root, change directory to ~/labs/lab1/ and cat out the Dockerfile

Need to add instructions about how to get that, where it's sync'd from, or where to clone it from.  I'll go ahead and clone it onto the vagrant host so I can continue.

**Comment by dustymabe** [comment]
Are you using the vagrantfile from the git repo? The folder should be synced already 
https://github.com/dustymabe/summit-2016-container-lab/blob/a4aa8edfdfe1078afe04a124244b3cb7f1623564/vagrantcdk/Vagrantfile#L31

we need a higher level intro to the CDK section to talk about vagrant and synced folders I think (I believe I had given @whitel  an action for doing something like this).

That being said I do need to cleanup the start of each lab to more clearly spell out that we are using a vagrant box and what directory the Vagrantfile is in.

**Comment by scollier** [comment]
i was using the vagrantfile from the CDK.  will switch over.

**Comment by scollier** [comment]
worked today with no issues.
