### ISSUE TITLE
registry for images

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2016-container-lab#5]
I was able to pull the rhel7.1 image, but that's because I was online.  We'll need to deploy a registry that the students can hit and put the right images there.  Then document the path to those images.

**Comment by dustymabe** [comment]
None of our dockerfiles should be still pulling rhel7.1 should be 7.2 now. 

Either way hosting a registry is an open item right now. Going to try to figure that out this week too.

**Comment by dustymabe** [comment]
For the lab for summit we are now using the vagrantRepoHost box to serve a docker registry for registry.access.redhat.com
