### ISSUE TITLE
Error running apache container

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2016-container-lab#7]
When I copied the docker run command, recieved an error that the port was already in use:

```
$ docker run -dt -p 80:80 --name apache redhat/apache
d9db5d82c9100a4588aa12d058e05c69ec9c9d46e036391886cbe53c29294a7f
Error response from daemon: Cannot start container d9db5d82c9100a4588aa12d058e05c69ec9c9d46e036391886cbe53c29294a7f: failed to create endpoint apache on network bridge: Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use
```

some conflict with openshift?

This issue blocks the next several commands.

I did a:

```
systemctl stop openshift
```

And then I was able to run the container and continue.

**Comment by dustymabe** [comment]
The vagrantfile we are using won't start openshift on bringup:
https://github.com/dustymabe/summit-2016-container-lab/blob/master/vagrantcdk/Vagrantfile

we'll `systemctl start openshift` in lab 3.

**Comment by scollier** [comment]
i was using vagrantfile from cdk, will switch over and run through it again

**Comment by scollier** [comment]
i did not have an issue with this today.
